WebMarket/Areas/Customer/Controllers/DemonstrProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebMarket.DbData;
using WebMarket.Models;

namespace WebMarket.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class DemonstrProductController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRepository<Product> _productsRepository;

        public DemonstrProductController(ILogger<HomeController> logger, IRepository<Product> productsRepository)
        {
            _logger = logger;
            _productsRepository = productsRepository;
        }

     
        public IActionResult AllProductsDemoList()
        {
            var productList = _productsRepository.GetAll().ToList();
            return View(productList);
        }

      
    }
}

WebMarket/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebMarket.DbData;
using WebMarket.Models;

namespace WebMarket.Controllers
{
    public class ProductController:Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IRepository<Product> _productsRepository;
        public ProductController(IWebHostEnvironment webHostEnvironment, IRepository<Product> productsRepository)
        {
            _webHostEnvironment= webHostEnvironment;
            _productsRepository= productsRepository;
        }
        public IActionResult Index() 
        {
            var productList = _productsRepository.GetAll().ToList();
            return View(productList);
        }
        public IActionResult UpSert(int? prodId)
        {
            Product Product = _productsRepository.Get(x => x.Id == prodId);
           
            if (prodId == null || prodId == 0)
            {
                Product=new Product();
             
            }
            return View(Product);
            

        }
        [HttpPost]
        public IActionResult UpSert(Product Product, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRotPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string productPath = Path.Combine(wwwRotPath, @"images\product");
                    if (!string.IsNullOrEmpty(Product.ImageUrl))
                    {
                        var oldImage = Path.Combine(wwwRotPath, Product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImage))
                        {
                            System.IO.File.Delete(oldImage);
                        }
                    }
                    using (var filestrim = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                    {
                        file.CopyTo(filestrim);
                    }
                    Product.ImageUrl = @"\images\product\" + fileName;
                }
                if (Product.Id == 0)
                {
                    _productsRepository.Add(Product);
                }
                else
                {
                    _productsRepository.Update(Product);
                }

                _productsRepository.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            else
            {
               
                return View(Product);
            }
        }
    }
}

WebMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMarket.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
           
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="DemonstrProduct" asp-action="AllProductsDemoList">Auction-Market</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Seller"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Prodcuts</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
            
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebMarket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
 